### ISSUE TITLE
Logo licensing

### ISSUE THREAD

**Issue by aredridel** [krakenjs/krakenjs.github.io#20]
I was asked today whether someone could use our logo when referring to Kraken.

It'd be nice to clarify that policy at least in English if not legalese. Trademark and copyright law. Ewww.

**Comment by lmarkus** [comment]
@aredridel 
Admittedly, the wording I chose when creating the original site was not very clear:
`Documentation licensed under Creative Commons Attribution 4.0 International License`
The intent was for everything in the site to be under CC4.0; (including the graphics).

I no longer have the email chain, but eBay legal was pretty much ok with this.

**Comment by aredridel** [comment]
Awesome. That'll do I think.
