### ISSUE TITLE
Missing components in the HellowWorld app

### ISSUE THREAD

**Issue by viswanathankasi** [krakenjs/krakenjs.github.io#30]
I did install the below components, after which the app worked.

dustjs-helpers
less
localizr

**Comment by aredridel** [comment]
Sounds like npm didn't install everything. Are you running an npm version < 1.4.28? (2.5.0 is even better!)

**Comment by viswanathankasi** [comment]
npm: '1.4.14'

**Comment by aredridel** [comment]
That version of npm has race conditions in it that will fail to unpack things sometimes.

Upgrade to 2.5.1 or 2.6.0.
