### ISSUE TITLE
layout issues with navigation in Chrome

### ISSUE THREAD

**Issue by grawk** [krakenjs/krakenjs.github.io#35]
In desktop view (only in Chrome) you can reproduce this layout quirk:

![krakenjs com chrome nav layout top](https://cloud.githubusercontent.com/assets/1031360/7145048/544e38d6-e29e-11e4-8922-98162d0dc71c.png)

And scrolling to the bottom you can reproduce this:
![krakenjs com chrome nav layout bottom](https://cloud.githubusercontent.com/assets/1031360/7145083/8500f770-e29e-11e4-9ed9-b315a79ad437.png)

**Comment by pavelloz** [comment]
@grawk can you specify OSX version/Chrome version and steps to reproduce, if you can come up with any?

I tried to reproduce it on OSX Capitain/Chrome 49 and i managed to what you have pasted on the first screenshot, but only for a second, after i resized window i went back to normal. Now i cant reproduce it again :)

I couldn't achieve effect from screenshot no. 2 at all.

**Comment by grawk** [comment]
I can't reproduce the problem any longer, either. I also have Chrome v49. Must have been something in a recent build that resolved it...

**Comment by grawk** [comment]
Closing.

**Comment by grawk** [comment]
Thanks for taking the time to look at this @pavelloz

**Comment by pavelloz** [comment]
Ouh, i just found out that second issue was fixed in here: https://github.com/krakenjs/krakenjs.github.io/pull/42/commits/614b49f9652d4f1da206be00259ab1f3ead5d2b8
