### ISSUE TITLE
Menu overlaps content in narrow window chrome

### ISSUE THREAD

**Issue by aredridel** [krakenjs/krakenjs.github.io#37]
![screen shot 2015-06-22 at 10 47 00 am](https://cloud.githubusercontent.com/assets/2876/8284673/20c35942-18cc-11e5-9390-d3758cae78ec.png)

**Comment by jasisk** [comment]
I swear I fixed this once. :\

**Comment by grawk** [comment]
Something about the .affix class (adding `position: fixed` to div#documentation-nav) is doing this.  Somehow that's doing away with calculating the 25% width correctly?

**Comment by grawk** [comment]
Adding a smaller percentage width as below kind of resolves this:
```css
#documentation-nav .affix {
	top: 0;
    width: 13%;
}
```

I assume that somehow the interaction of position:fixed and top:0 conspire to calculate the 25% width based on the actual window size and not the parent container (.container).

But, when you keep shrinking the window, the nav becomes unusually narrow.

**Comment by aredridel** [comment]
Sounds about right.
