### ISSUE TITLE
Get started and Latest News link dont show up on production

### ISSUE THREAD

**Issue by pavelloz** [krakenjs/krakenjs.github.io#61]
While i was testing https://github.com/krakenjs/krakenjs.github.io/pull/60 i noticed that the homepage on my machine is different than on production. I went into code and found out that condition `{% if page.url == '/index.html' %}` is never met on production, but it is met on localhost .

To reproduce on localhost, just build a page and open index.html
To reproduce on production, go to http://krakenjs.com/index.html

![image](https://cloud.githubusercontent.com/assets/546845/14354583/27750348-fcde-11e5-82e3-12759be3f012.png)
![image](https://cloud.githubusercontent.com/assets/546845/14354592/320a4e3a-fcde-11e5-95dd-e8f9f4be8f70.png)

I tested it on both engines to rule out kramdown migration as a problem.

This is also true for other conditions that are checking if the page.url is index.html, especially switching on/off the link to the homepage called KrakenJS

**Comment by grawk** [comment]
Hm. That worked just a few weeks ago. Even in production. Thanks for filing this.

**Comment by pavelloz** [comment]
I wouldnt be surprised if it broke just because github changes in github pages or jekyll update.

I see that you include only `githubpages` gem in your gemfile and then it is including all dependencies. This way you have no control over jekyll version (which means, you always use whatever version githubpages gem author is using). 

Its a tradeoff, having everything up to date can result in some regressions if you dont pay attention to X changelogs :)

**Comment by grawk** [comment]
Looks like `page.url` is set as `/` instead of `/index.html`. Easy fix. Not sure when that changed or how exactly... Do you think you can add that as part of your PR changing to kramdown? I've tested this locally and it looks good. If you can include the change then that resolves this issue as well.

**Comment by grawk** [comment]
In fact, let me just resolve this quickly now. The site is missing a large chunk of header content without the fix. I'm incorporating your commits into an upcoming PR.
